### ISSUE TITLE
Link type column data reset after row update

### ISSUE THREAD

**Issue by Jednadvacet** [nextcloud/tables#1036]
### Steps to reproduce

1. Fill data column of existing row. The column type should be link. My row has three link fields.
2. Save row.
3. Row saved. Link fields are cleared. 

### Expected behavior

Row update saves all fields.

### Actual behavior

Link fields are cleared.

### Tables app version

0.7.1.

### Browser

Edge

### Operating system

Ubuntu 20.04

### Web server

Nginx

### PHP engine version

PHP 8.1

### Database

PostgreSQL

**Comment by Jednadvacet** [comment]
Seems that the issue is connected with charset. Typical Czech language characters ščřžýáíěé in a link title call this errror:

```Value {"title":"Ing. Tom\u00e1\u0161 \u0160enky\u0159\u00edk","value":"https:\/\/cloud.lbtechnet.cz\/apps\/contacts\/direct\/contact\/b08ce89e-2f35-48e5-b499-484a23185658~contacts","providerId":"url"} cannot be parsed as the column 52 does not allow the provider: url```

New row is saved properly, update resets.

**Comment by Jednadvacet** [comment]
Quick fix: Link type fields should have at least 2 subtypes (eg. Files + Url). 
Saving rows doesn't clear other link fields anymore.

**Comment by juliushaertl** [comment]
Thanks, we should of course fix that to not empty the value and provide a proper hint on why that fails.

**Comment by juliushaertl** [comment]
Might be worth to reconsider if the subtypes should actually limit what you can insert into an URL field or if those should just be used for search suggestions.

**Comment by lars-becker** [comment]
> Quick fix: Link type fields should have at least 2 subtypes (eg. Files + Url). Saving rows doesn't clear other link fields anymore.

Thanks that solved the problem with repeated **data** **loss** for us. This problem should be fixed ASAP.

**Comment by ISC-PRO** [comment]
> Quick fix: Link type fields should have at least 2 subtypes (eg. Files + Url). Saving rows doesn't clear other link fields anymore.

That was very helpful, thank you very much! Please fix it quickly.

**Comment by bentuna** [comment]
This Issue still persists under Nextcloud 29.0.8 and Tables 0.8.1.

**Comment by ISC-PRO** [comment]
Good morning. Can you tell me what the further planning looks like?

**Comment by enjeck** [comment]
should be now fixed
